### ISSUE TITLE
Made payment file received 

### ISSUE THREAD

**Issue by mahsan20** [likhonsible/Flash-USDT-Sender-Software-Free-Activation-Code#15]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by likhonsible** [comment]
Complete

**Comment by mahsan20** [comment]
After taking the payments no response

**Comment by mahsan20** [comment]
Yes
